server.port=9092
spring.application.name=edith-ach-backend

# SAML SP Configuration
saml.sp.entity-id=http://localhost:4001/saml/metadata
saml.idp.entity-id=http://localhost:3000/saml/metadata
saml.idp.cert-path=classpath:saml/idp-cert.pem
