server.port=9094
spring.application.name=jarvis-bank-backend

# SAML IdP Configuration
saml.idp.entity-id=http://localhost:5001/saml/metadata
saml.idp.cert-path=classpath:saml/jarvis-idp-cert.pem
saml.idp.key-path=classpath:saml/jarvis-idp-key.pem

# Registered Service Provider (edith-core)
saml.sp.core.entity-id=http://localhost:3000/saml/metadata
saml.sp.core.acs-url=http://localhost:3000/saml/acs
