server.port=9091
spring.application.name=edith-rdc-backend

# SAML SP Configuration
saml.sp.entity-id=http://localhost:4000/saml/metadata
saml.idp.entity-id=http://localhost:3000/saml/metadata
saml.idp.cert-path=classpath:saml/idp-cert.pem
